### ISSUE TITLE
Cant register IP address along with hostname

### ISSUE THREAD

**Issue by deepande** [sous-chefs/zabbix-agent#5]
I am using this cookbook to register my aws instance as an agent to my Zabbix server through AWS opsworks. I am using JSON settings to override the configuration as below. The recipe runlist I am using is **zabbix-agent** and **zabbix-agent::agent_registration**.

When I use only **zabbix-agent**, the agent gets installed and registered to Zabbix server , but the ip address does not get register. When I include the recipe **zabbix-agent::agent_registration** in my run list I get the below error.

Recipe Compile Error in /var/lib/aws/opsworks/cache.stage2/cookbooks/zabbix-agent/recipes/agent_registration.rb

**NoMethodError**

undefined method `[]' for nil:NilClass

**Cookbook Trace:**

/var/lib/aws/opsworks/cache.stage2/cookbooks/zabbix-agent/recipes/agent_registration.rb:21:in `from_file'

**Relevant File Content:**

/var/lib/aws/opsworks/cache.stage2/cookbooks/zabbix-agent/recipes/agent_registration.rb:

20:  connection_info = {
**21>>   url: "http://#{zabbix_server['zabbix']['web']['fqdn']}/api_jsonrpc.php",**
22:    user: zabbix_server['zabbix']['web']['login'],
23:    password: zabbix_server['zabbix']['web']['password']
24:  }

<h3>JSON settings specified</h3> (**Not sure about the ip address paramaters as its not working yet** )
_{
  "node": {
    "ipaddress": "some-ip",
    "fqdn": "zabix-web-url",
    "network": {
      "interfaces": {
        "zabbix_agent": {
          "type": "1",
          "main": "1",
          "useip": "1",
          "ip": "ipaddress"
        }
      }
    },
    "zabbix": {
      "web": {
        "fqdn": "zabix-web-url",
        "login": "username",
        "password": "password"
      },
      "agent": {
        "version": "2.4.2",
        "network_interface": "true",
        "interfaces": {
        "zabbix_agent": {
          "type": "1",
          "main": "1",
          "useip": "1",
          "ip": "ipaddress"
        }
      }
    },
      "conf": {
        "HostMetadataItem": "system.run[uname]",
        "HostnameItem": "system.run[hostname]",
        "LogFile": "/var/log/zabbix/zabbix_agentd.log",
        "Server": "zabbix-server-ip",
        "ServerActive": "zabbix-server-ip",
        "Timeout": "10"
      }
    }
  }
}_

**Comment by TD-4242** [comment]
Sorry I haven't gotten to this yet.  That code was pulled over from the original project and I have not gone through to clean it up yet.   It depends on some code that was moved to the libzabbix lwrp cookbook so right now it wont work at all.

**Comment by AnuragRamdasan** [comment]
It would be cool to get it to work. Is there a workaround you can suggest for this to get running now?

**Comment by TD-4242** [comment]
As it is, the code hasn't been ported over so it will not work.  if you want to start porting it over to libzabbix that would be great.
